spring.application.name=api

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/safenews}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:safenews}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:safenews}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

spring.flyway.enabled=true
